In [5]:
# Import necessary Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score, recall_score, f1_score
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
import joblib
from pathlib import Path

In [13]:
# Set the main project folder
PROJECT_DIR = Path.cwd().parent

# Define the Task B dataset folders
task_a_path = PROJECT_DIR / "Data" / "TaskA - modified set"

# Read the dataset
df=pd.read_csv(task_a_path / "training" / "english" / "taskA_training_en.tsv",sep="\t")

# Shape of the Dataset

print("Shape of the dataset:", df.shape)

# Display the First 5 Rows of the Dataset
df.head()

Shape of the dataset: (28879, 4)

,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978-e45c-4f28-b859-7f89221b0505,air commodore,flight lieutenant
0,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,command and control officer,flight officer
1,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,air commodore,command and control officer
2,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,pilot officer,squadron leader
3,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,royal airforce officer,command and control officer
4,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,squadron leader,command and control officer

In [3]:
# Rename the Columns of the Dataset
df.columns = ["isco","occupation_uri","jobtitle_1","jobtitle_2"]
df.head()

,isco,occupation_uri,jobtitle_1,jobtitle_2
0,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,air commodore,flight lieutenant
1,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,command and control officer,flight officer
2,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,air commodore,command and control officer
3,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,pilot officer,squadron leader
4,http://data.europa.eu/esco/isco/C0110,http://data.europa.eu/esco/occupation/f2cc5978...,royal airforce officer,command and control officer

In [4]:
# Display the Columns and Information of the Dataset
print(df.columns)
# Display the Information of the Dataset
print(df.info())

Index(['isco', 'occupation_uri', 'jobtitle_1', 'jobtitle_2'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 28880 entries, 0 to 28879
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isco            28880 non-null  str
 1   occupation_uri  28880 non-null  str
 2   jobtitle_1      28880 non-null  str
 3   jobtitle_2      28880 non-null  str
dtypes: str(4)
memory usage: 5.3 MB
None

In [5]:
# Display the Unique Values of the Datase
print("Unique ISCO codes:", df['isco'].nunique())
print("Unique occupation URIs:", df['occupation_uri'].nunique())
print("Unique jobtitle_1:", df['jobtitle_1'].nunique())
print("Unique jobtitle_2:", df['jobtitle_2'].nunique())

Unique ISCO codes: 424
Unique occupation URIs: 3011
Unique jobtitle_1: 18863
Unique jobtitle_2: 18754

In [6]:
# Check for Duplicate Rows in the Dataset
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [7]:
# Check for Duplicate Title Pairs in the Dataset
print("Duplicate title pairs:", df[['jobtitle_1', 'jobtitle_2']].duplicated().sum())

Duplicate title pairs: 16

In [8]:
# Find all rows where the same pair of job titles occurs more than once
duplicate_pairs = df[df.duplicated(
    subset=['jobtitle_1', 'jobtitle_2'],
    keep=False
)]

# Sort the duplicate pairs for easier inspection
duplicate_pairs.sort_values(
    ['jobtitle_1', 'jobtitle_2']
)

,isco,occupation_uri,jobtitle_1,jobtitle_2
14289,http://data.europa.eu/esco/isco/C3153,http://data.europa.eu/esco/occupation/523ab5a0...,airline pilot,captain
14299,http://data.europa.eu/esco/isco/C3153,http://data.europa.eu/esco/occupation/522c55ca...,airline pilot,captain
20830,http://data.europa.eu/esco/isco/C6112,http://data.europa.eu/esco/occupation/b865693a...,arboriculturist,arborist
20928,http://data.europa.eu/esco/isco/C6113,http://data.europa.eu/esco/occupation/fa30c1cb...,arboriculturist,arborist
14079,http://data.europa.eu/esco/isco/C3141,http://data.europa.eu/esco/occupation/f3b99acc...,biochemistry technologist,chemistry technician
14087,http://data.europa.eu/esco/isco/C3141,http://data.europa.eu/esco/occupation/95324a4a...,biochemistry technologist,chemistry technician
419,http://data.europa.eu/esco/isco/C1211,http://data.europa.eu/esco/occupation/30f3ea93...,chief financial officer,CFO
431,http://data.europa.eu/esco/isco/C1211,http://data.europa.eu/esco/occupation/b680251e...,chief financial officer,CFO
1150,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/3afd6af4...,clothing operations area manager,clothing operations director
1294,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/518348e6...,clothing operations area manager,clothing operations director
1151,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/3afd6af4...,clothing production manager,clothing operations area manager
1299,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/518348e6...,clothing production manager,clothing operations area manager
4212,http://data.europa.eu/esco/isco/C2133,http://data.europa.eu/esco/occupation/e8461d2e...,environmental conservation technician,environmental protection technician
4230,http://data.europa.eu/esco/isco/C2133,http://data.europa.eu/esco/occupation/7af81505...,environmental conservation technician,environmental protection technician
1164,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/6482664d...,fashion production manager,production planning manager
1198,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/e5257110...,fashion production manager,production planning manager
4898,http://data.europa.eu/esco/isco/C2145,http://data.europa.eu/esco/occupation/4b709f9e...,food technology expert,food tech specialist
13105,http://data.europa.eu/esco/isco/C3119,http://data.europa.eu/esco/occupation/afee6a28...,food technology expert,food tech specialist
4899,http://data.europa.eu/esco/isco/C2145,http://data.europa.eu/esco/occupation/4b709f9e...,food technology expert,food technology specialist
13112,http://data.europa.eu/esco/isco/C3119,http://data.europa.eu/esco/occupation/afee6a28...,food technology expert,food technology specialist
4894,http://data.europa.eu/esco/isco/C2145,http://data.europa.eu/esco/occupation/4b709f9e...,food technology specialist,food tech expert
13107,http://data.europa.eu/esco/isco/C3119,http://data.europa.eu/esco/occupation/afee6a28...,food technology specialist,food tech expert
13976,http://data.europa.eu/esco/isco/C3134,http://data.europa.eu/esco/occupation/d26a941d...,gas distribution system operative,gas distribution system worker
18802,http://data.europa.eu/esco/isco/C4323,http://data.europa.eu/esco/occupation/555ad9ba...,gas distribution system operative,gas distribution system worker
21701,http://data.europa.eu/esco/isco/C7211,http://data.europa.eu/esco/occupation/dc14bed4...,ladleman,foundry operator
25164,http://data.europa.eu/esco/isco/C8121,http://data.europa.eu/esco/occupation/25206eaa...,ladleman,foundry operator
712,http://data.europa.eu/esco/isco/C1219,http://data.europa.eu/esco/occupation/680831bb...,manufacturing plant manager,manufacturing director
1121,http://data.europa.eu/esco/isco/C1321,http://data.europa.eu/esco/occupation/6426ada1...,manufacturing plant manager,manufacturing director
24651,http://data.europa.eu/esco/isco/C7543,http://data.europa.eu/esco/occupation/61d9270c...,product quality monitor,product quality inspector
24843,http://data.europa.eu/esco/isco/C7543,http://data.europa.eu/esco/occupation/cc8f929a...,product quality monitor,product quality inspector
14243,http://data.europa.eu/esco/isco/C3152,http://data.europa.eu/esco/occupation/f2a416b8...,shipmaster,ship captain
14248,http://data.europa.eu/esco/isco/C3152,http://data.europa.eu/esco/occupation/ee646fa1...,shipmaster,ship captain

In [9]:
# Count how many times each occupation URI appears
print(df['occupation_uri'].value_counts().describe())

count    3011.000000
mean        9.591498
std         1.544204
min         1.000000
25%        10.000000
50%        10.000000
75%        10.000000
max        10.000000
Name: count, dtype: float64

In [10]:
# Count how many occupation classes have fewer than 10 records
occupation_counts = df['occupation_uri'].value_counts()

print("Occupations with less than 10 records:",
      (occupation_counts < 10).sum())

Occupations with less than 10 records: 220

In [11]:
# Show how many occupation classes have each low frequency
print(occupation_counts[occupation_counts < 10].value_counts().sort_index())

count
1     31
3     65
6    124
Name: count, dtype: int64

In [12]:
# Find the minimum character length of jobtitle_1
print("Shortest jobtitle_1 length:",
      df['jobtitle_1'].str.len().min())

# Find the minimum character length of jobtitle_2
print("Shortest jobtitle_2 length:",
      df['jobtitle_2'].str.len().min())

Shortest jobtitle_1 length: 2
Shortest jobtitle_2 length: 2

In [13]:
# Display unique jobtitle_1 values containing only 2 characters
print(
    df.loc[
        df['jobtitle_1'].str.len() == 2,
        'jobtitle_1'
    ].unique()
)

# Display unique jobtitle_2 values containing only 2 characters

print(
    df.loc[
        df['jobtitle_2'].str.len() == 2,
        'jobtitle_2'
    ].unique()
)

<ArrowStringArray>
['QS', 'TA', 'DJ', 'PI', 'SD', 'AB', 'OS', 'KP']
Length: 8, dtype: str
<ArrowStringArray>
['TA', 'DJ', 'PA', 'AB', 'OS', 'KP']
Length: 6, dtype: str

In [14]:
# Check how many jobtitle_1 values contain leading or trailing spaces
print(
    "jobtitle_1 with extra spaces:",
    (df['jobtitle_1'] != df['jobtitle_1'].str.strip()).sum()
)

# Check how many jobtitle_2 values contain leading or trailing spaces
print(
    "jobtitle_2 with extra spaces:",
    (df['jobtitle_2'] != df['jobtitle_2'].str.strip()).sum()
)

jobtitle_1 with extra spaces: 63
jobtitle_2 with extra spaces: 62

In [15]:
# Create a separate copy so that the original dataset remains unchanged
df_preprocessed = df.copy()

In [16]:
# Convert Job Titles into Lowercase
df_preprocessed['jobtitle_1'] = df_preprocessed['jobtitle_1'].str.lower()
df_preprocessed['jobtitle_2'] = df_preprocessed['jobtitle_2'].str.lower()

In [17]:
# Remove leading and trailing spaces from Job Titles
df_preprocessed['jobtitle_1'] = df_preprocessed['jobtitle_1'].str.strip()
df_preprocessed['jobtitle_2'] = df_preprocessed['jobtitle_2'].str.strip()

In [18]:
# Display the first 10 rows of the preprocessed job titles
df_preprocessed[['jobtitle_1', 'jobtitle_2']].head(10)

                    jobtitle_1                   jobtitle_2
0                air commodore            flight lieutenant
1  command and control officer               flight officer
2                air commodore  command and control officer
3                pilot officer              squadron leader
4       royal airforce officer  command and control officer
5              squadron leader  command and control officer
6       military group captain               flight officer
7              squadron leader               flight officer
8            flight lieutenant       royal airforce officer
9                air commodore              squadron leader

In [19]:
# Check whether jobtitle_1 or jobtitle_2 contains missing values
df_preprocessed[['jobtitle_1', 'jobtitle_2']].isna().sum()

jobtitle_1    0
jobtitle_2    0
dtype: int64

In [20]:
# Count how many samples are available for each occupation URI
class_counts = df_preprocessed['occupation_uri'].value_counts()

In [21]:
# Find occupation classes that have only one sample
rare_classes = class_counts[class_counts == 1].index

# Create a dataframe containing the single-sample classes
rare_df = df_preprocessed[
    df_preprocessed['occupation_uri'].isin(rare_classes)
]

# Create another dataframe containing all remaining classes
regular_df = df_preprocessed[
    ~df_preprocessed['occupation_uri'].isin(rare_classes)
]

In [22]:
# Display the number of rows and columns in the rare and regular datasets
print("Rare dataframe shape:", rare_df.shape)
print("Regular dataframe shape:", regular_df.shape)

Rare dataframe shape: (31, 4)
Regular dataframe shape: (28849, 4)

In [23]:
# Split the regular classes into training and testing data
train_regular, test_df = train_test_split(
    regular_df,
    test_size=0.2,
    random_state=42,
    stratify=regular_df['occupation_uri']
)

In [24]:
# Add all single-sample occupation classes to the training set
train_df = pd.concat(
    [train_regular, rare_df],
    ignore_index=True
)

In [25]:
# Display the final training and testing dataset size
print("Training set shape:", train_df.shape)
print("Testing set shape:", test_df.shape)

Training set shape: (23110, 4)
Testing set shape: (5770, 4)

In [26]:
# Find occupation classes that appear in the test set but do not appear in the training set
test_only_classes = set(test_df['occupation_uri']) - set(train_df['occupation_uri'])

# Display the number of test-only classes
print("Classes present only in test set:",len(test_only_classes))

Classes present only in test set: 0

In [27]:
# Create the TF-IDF vectorizer
tfidf = TfidfVectorizer()

# Combine both job-title columns from the training data so that both title columns use the same vocabulary
train_titles = pd.concat([train_df['jobtitle_1'],train_df['jobtitle_2']])

# Learn the vocabulary and IDF values from training data
tfidf.fit(train_titles)

TfidfVectorizer()

In [28]:
# Convert jobtitle_1 and jobtitle_2from the training set into TF-IDF features
X_train_title1 = tfidf.transform(train_df['jobtitle_1'])
X_train_title2 = tfidf.transform(train_df['jobtitle_2'])

In [29]:
# Convert jobtitle_1 and jobtitle_2from the test set using the vocabulary already learned from the training data
X_test_title1 = tfidf.transform(test_df['jobtitle_1'])
X_test_title2 = tfidf.transform(test_df['jobtitle_2'])

In [30]:
# Display the shapes of TF-IDF features for jobtitle_1 and jobtitle_2 in training and testing data
print("X_train_title1 shape:", X_train_title1.shape)
print("X_train_title2 shape:", X_train_title2.shape)
print("X_test_title1 shape:", X_test_title1.shape)
print("X_test_title2 shape:", X_test_title2.shape)

X_train_title1 shape: (23110, 5424)
X_train_title2 shape: (23110, 5424)
X_test_title1 shape: (5770, 5424)
X_test_title2 shape: (5770, 5424)

In [31]:
# Combine TF-IDF features of jobtitle_1 and jobtitle_2 for the training and testing data
X_train = hstack([X_train_title1,X_train_title2])
X_test = hstack([X_test_title1,X_test_title2])

In [32]:
# Display the final training and testing feature matrix shapes
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (23110, 10848)
X_test shape: (5770, 10848)

In [33]:
# Select occupation_uri as the target variable for training and testing
y_train = train_df['occupation_uri']
y_test = test_df['occupation_uri']

In [34]:
# Display the number of target values in the training set and testing set
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

y_train shape: (23110,)
y_test shape: (5770,)

In [35]:
# Create the label encoder
label_encoder = LabelEncoder()

# Learn the occupation classes from the training data and convert them into numerical labels
y_train_encoded = label_encoder.fit_transform(y_train)

# Convert test occupation URIs using the same encoder
y_test_encoded = label_encoder.transform(y_test)

In [36]:
# Display the total number of occupation classes
print("Number of classes:", len(label_encoder.classes_))

# Display the shape of encoded training and testing targets
print("y_train_encoded shape:", y_train_encoded.shape)
print("y_test_encoded shape:", y_test_encoded.shape)

Number of classes: 3011
y_train_encoded shape: (23110,)
y_test_encoded shape: (5770,)

In [37]:
# Create the Logistic Regression model
logistic_model = LogisticRegression(max_iter=1000,random_state=42)

In [38]:
# Train the Logistic Regression model using the Training Data
logistic_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [39]:
# Make predictions using the trained Logistic Regression Model
y_pred_logistic = logistic_model.predict(X_test)

# Display the first 10 predicted occupation classes
print("First 10 predictions:", y_pred_logistic[:10])

First 10 predictions: ['http://data.europa.eu/esco/occupation/1bb2aa65-1524-4961-8dba-ad25f34f195f'
 'http://data.europa.eu/esco/occupation/4fef1907-cf82-413b-841a-02ef57e299a6'
 'http://data.europa.eu/esco/occupation/65fb0b53-b8c4-4839-b099-c80b6de5a158'
 'http://data.europa.eu/esco/occupation/a273ec4c-96fd-48e5-9343-695a6bd08512'
 'http://data.europa.eu/esco/occupation/f89b12a1-689f-4a4f-8695-abb620810f1e'
 'http://data.europa.eu/esco/occupation/bcc199fe-f7df-42a5-bd45-e33ae6160f26'
 'http://data.europa.eu/esco/occupation/cb3b2662-774a-4e6f-841e-f120244d7031'
 'http://data.europa.eu/esco/occupation/b06a1dde-e5a1-4219-9491-2bedd0282e4b'
 'http://data.europa.eu/esco/occupation/1d70e660-1114-41c6-926a-053541460d88'
 'http://data.europa.eu/esco/occupation/2c83f279-a1d1-4c9f-a6aa-5e5ee1850e46']

In [40]:
# Calculate the accuracy of the Logistic Regression model
logistic_accuracy = accuracy_score(y_test, y_pred_logistic)

# Display the accuracy
print("Logistic Regression Accuracy:", logistic_accuracy)

Logistic Regression Accuracy: 0.8162911611785095

In [41]:
# Calculate weighted precision
logistic_precision = precision_score(
    y_test,
    y_pred_logistic,
    average='weighted',
    zero_division=0
)

# Calculate weighted recall
logistic_recall = recall_score(
    y_test,
    y_pred_logistic,
    average='weighted',
    zero_division=0
)

# Calculate weighted F1-score
logistic_f1 = f1_score(
    y_test,
    y_pred_logistic,
    average='weighted',
    zero_division=0
)

# Display the evaluation results
print("Logistic Regression Precision:", logistic_precision)
print("Logistic Regression Recall:", logistic_recall)
print("Logistic Regression F1-score:", logistic_f1)

Logistic Regression Precision: 0.8124065362713544
Logistic Regression Recall: 0.8162911611785095
Logistic Regression F1-score: 0.7916544249126573

In [42]:
# Create the Linear SVM model
svm_model = LinearSVC(C=1.0,random_state=42,max_iter=2000)

In [43]:
# Train the Linear SVM model using the training TF-IDF features
svm_model.fit(X_train, y_train)

LinearSVC(max_iter=2000, random_state=42)

In [44]:
# Make predictions on the unseen test data using the trained Linear SVM model
y_pred_svm = svm_model.predict(X_test)

# Display the first 10 predictions to verify that the model is working
print("First 10 SVM predictions:", y_pred_svm[:10])

First 10 SVM predictions: ['http://data.europa.eu/esco/occupation/1bb2aa65-1524-4961-8dba-ad25f34f195f'
 'http://data.europa.eu/esco/occupation/31cc4199-703c-4f8a-9b46-a2070a6d35df'
 'http://data.europa.eu/esco/occupation/65fb0b53-b8c4-4839-b099-c80b6de5a158'
 'http://data.europa.eu/esco/occupation/a273ec4c-96fd-48e5-9343-695a6bd08512'
 'http://data.europa.eu/esco/occupation/f89b12a1-689f-4a4f-8695-abb620810f1e'
 'http://data.europa.eu/esco/occupation/bcc199fe-f7df-42a5-bd45-e33ae6160f26'
 'http://data.europa.eu/esco/occupation/cb3b2662-774a-4e6f-841e-f120244d7031'
 'http://data.europa.eu/esco/occupation/b06a1dde-e5a1-4219-9491-2bedd0282e4b'
 'http://data.europa.eu/esco/occupation/1d70e660-1114-41c6-926a-053541460d88'
 'http://data.europa.eu/esco/occupation/2c83f279-a1d1-4c9f-a6aa-5e5ee1850e46']

In [45]:
# Calculate the accuracy of the Linear SVM model
svm_accuracy = accuracy_score(y_test, y_pred_svm)

# Display the accuracy
print("Linear SVM Accuracy:", svm_accuracy)

Linear SVM Accuracy: 0.891161178509532

In [46]:
# Calculate Precision, Recall, and F1-score for the Linear SVM model
svm_precision = precision_score(
    y_test,
    y_pred_svm,
    average='weighted',
    zero_division=0
)

svm_recall = recall_score(
    y_test,
    y_pred_svm,
    average='weighted',
    zero_division=0
)

svm_f1 = f1_score(
    y_test,
    y_pred_svm,
    average='weighted',
    zero_division=0
)

# Display the evaluation results
print("Linear SVM Precision:", svm_precision)
print("Linear SVM Recall:", svm_recall)
print("Linear SVM F1-score:", svm_f1)

Linear SVM Precision: 0.9004968226458695
Linear SVM Recall: 0.891161178509532
Linear SVM F1-score: 0.880312783692333

In [47]:
# Create the Multinomial Naive Bayes model
nb_model = MultinomialNB(alpha=1.0)

In [48]:
# Train the Multinomial Naive Bayes model using the training TF-IDF features
nb_model.fit(X_train,y_train)

MultinomialNB()

In [49]:
# Make predictions on the unseen test data using the trained Naive Bayes model
y_pred_nb = nb_model.predict(X_test)

# Display the first 10 predictions to verify that the model is working
print("First 10 Naive Bayes predictions:", y_pred_nb[:10])

First 10 Naive Bayes predictions: ['http://data.europa.eu/esco/occupation/1bb2aa65-1524-4961-8dba-ad25f34f195f'
 'http://data.europa.eu/esco/occupation/4fef1907-cf82-413b-841a-02ef57e299a6'
 'http://data.europa.eu/esco/occupation/65fb0b53-b8c4-4839-b099-c80b6de5a158'
 'http://data.europa.eu/esco/occupation/a273ec4c-96fd-48e5-9343-695a6bd08512'
 'http://data.europa.eu/esco/occupation/f89b12a1-689f-4a4f-8695-abb620810f1e'
 'http://data.europa.eu/esco/occupation/bcc199fe-f7df-42a5-bd45-e33ae6160f26'
 'http://data.europa.eu/esco/occupation/cb3b2662-774a-4e6f-841e-f120244d7031'
 'http://data.europa.eu/esco/occupation/b06a1dde-e5a1-4219-9491-2bedd0282e4b'
 'http://data.europa.eu/esco/occupation/1d70e660-1114-41c6-926a-053541460d88'
 'http://data.europa.eu/esco/occupation/2c83f279-a1d1-4c9f-a6aa-5e5ee1850e46']

In [50]:
# Calculate the accuracy of the Multinomial Naive Bayes model
nb_accuracy = accuracy_score(y_test, y_pred_nb)

# Display the accuracy

print("Multinomial Naive Bayes Accuracy:", nb_accuracy)

Multinomial Naive Bayes Accuracy: 0.8672443674176776

In [51]:
# Calculate Precision, Recall, and F1-score for the Naive Bayes model
nb_precision = precision_score(
    y_test,
    y_pred_nb,
    average='weighted',
    zero_division=0
)

nb_recall = recall_score(
    y_test,
    y_pred_nb,
    average='weighted',
    zero_division=0
)

nb_f1 = f1_score(
    y_test,
    y_pred_nb,
    average='weighted',
    zero_division=0
)

# Display all three evaluation metrics

print("Multinomial Naive Bayes Precision:", nb_precision)
print("Multinomial Naive Bayes Recall:", nb_recall)
print("Multinomial Naive Bayes F1-score:", nb_f1)

Multinomial Naive Bayes Precision: 0.8697177519187917
Multinomial Naive Bayes Recall: 0.8672443674176776
Multinomial Naive Bayes F1-score: 0.849258617369536

In [52]:
# Create a comparison table for all three classification models
model_results = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Linear SVM',
        'Multinomial Naive Bayes'
    ],
    'Accuracy': [
        logistic_accuracy,
        svm_accuracy,
        nb_accuracy
    ],
    'Precision': [
        logistic_precision,
        svm_precision,
        nb_precision
    ],
    'Recall': [
        logistic_recall,
        svm_recall,
        nb_recall
    ],
    'F1-score': [
        logistic_f1,
        svm_f1,
        nb_f1
    ]
})

# Display the comparison table
model_results

                     Model  Accuracy  Precision    Recall  F1-score
0      Logistic Regression  0.816291   0.812407  0.816291  0.791654
1               Linear SVM  0.891161   0.900497  0.891161  0.880313
2  Multinomial Naive Bayes  0.867244   0.869718  0.867244  0.849259

In [54]:
# We are testing a small range to find a better setting without making the search unnecessarily large
param_grid = {
    'C': [0.1, 0.5, 1.0, 2.0, 5.0]
    }

# Display the hyperparameter values that will be tested
print("C values to test:", param_grid['C'])

C values to test: [0.1, 0.5, 1.0, 2.0, 5.0]

In [55]:
# Create the Linear SVM model that GridSearchCV will tune
svm_grid = GridSearchCV(
    estimator=LinearSVC(
        random_state=42,
        max_iter=2000
    ),
    param_grid=param_grid,
    cv=3,
    scoring='f1_weighted',
    n_jobs=-1
)

In [56]:
# Run GridSearchCV on the training data
svm_grid.fit(X_train, y_train)

C:\Users\jagad\AppData\Roaming\Python\Python311\site-packages\sklearn\model_selection\_split.py:812: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

GridSearchCV(cv=3, estimator=LinearSVC(max_iter=2000, random_state=42),
             n_jobs=-1, param_grid={'C': [0.1, 0.5, 1.0, 2.0, 5.0]},
             scoring='f1_weighted')

In [57]:
# Display the best C value found by GridSearchCV
print("Best C:", svm_grid.best_params_['C'])

# Display the best weighted F1-score obtained during cross-validation
print("Best cross-validation F1-score:", svm_grid.best_score_)

Best C: 5.0
Best cross-validation F1-score: 0.8177533134122198

In [58]:
# Use the best Linear SVM model found by GridSearchCV
y_pred_svm_tuned = svm_grid.best_estimator_.predict(X_test)

# Display the first 10 predictions to confirm that the tuned model is working
print("First 10 tuned SVM predictions:", y_pred_svm_tuned[:10])

First 10 tuned SVM predictions: ['http://data.europa.eu/esco/occupation/1bb2aa65-1524-4961-8dba-ad25f34f195f'
 'http://data.europa.eu/esco/occupation/f3b99acc-b212-45cf-bb4f-7b83cc6f0d71'
 'http://data.europa.eu/esco/occupation/65fb0b53-b8c4-4839-b099-c80b6de5a158'
 'http://data.europa.eu/esco/occupation/a273ec4c-96fd-48e5-9343-695a6bd08512'
 'http://data.europa.eu/esco/occupation/f89b12a1-689f-4a4f-8695-abb620810f1e'
 'http://data.europa.eu/esco/occupation/bcc199fe-f7df-42a5-bd45-e33ae6160f26'
 'http://data.europa.eu/esco/occupation/cb3b2662-774a-4e6f-841e-f120244d7031'
 'http://data.europa.eu/esco/occupation/b06a1dde-e5a1-4219-9491-2bedd0282e4b'
 'http://data.europa.eu/esco/occupation/1d70e660-1114-41c6-926a-053541460d88'
 'http://data.europa.eu/esco/occupation/2c83f279-a1d1-4c9f-a6aa-5e5ee1850e46']

In [59]:
# Calculate Accuracy, Precision, Recall, and F1-score for the tuned Linear SVM
tuned_svm_accuracy = accuracy_score(y_test, y_pred_svm_tuned)

tuned_svm_precision = precision_score(
    y_test,
    y_pred_svm_tuned,
    average='weighted',
    zero_division=0
)

tuned_svm_recall = recall_score(
    y_test,
    y_pred_svm_tuned,
    average='weighted',
    zero_division=0
)

tuned_svm_f1 = f1_score(
    y_test,
    y_pred_svm_tuned,
    average='weighted',
    zero_division=0
)

# Display the test-set performance of the tuned model
print("Tuned Linear SVM Accuracy:", tuned_svm_accuracy)
print("Tuned Linear SVM Precision:", tuned_svm_precision)
print("Tuned Linear SVM Recall:", tuned_svm_recall)
print("Tuned Linear SVM F1-score:", tuned_svm_f1)

Tuned Linear SVM Accuracy: 0.8935875216637782
Tuned Linear SVM Precision: 0.9025534373194686
Tuned Linear SVM Recall: 0.8935875216637782
Tuned Linear SVM F1-score: 0.8829454485433689

In [60]:
# Add the tuned Linear SVM results to the model comparison table
tuned_svm_result = pd.DataFrame({
    'Model': ['Tuned Linear SVM'],
    'Accuracy': [tuned_svm_accuracy],
    'Precision': [tuned_svm_precision],
    'Recall': [tuned_svm_recall],
    'F1-score': [tuned_svm_f1]
})

# Combine the original model results with the tuned SVM results
model_results = pd.concat(
    [model_results, tuned_svm_result],
    ignore_index=True
)

# Display the complete comparison table
model_results

                     Model  Accuracy  Precision    Recall  F1-score
0      Logistic Regression  0.816291   0.812407  0.816291  0.791654
1               Linear SVM  0.891161   0.900497  0.891161  0.880313
2  Multinomial Naive Bayes  0.867244   0.869718  0.867244  0.849259
3         Tuned Linear SVM  0.893588   0.902553  0.893588  0.882945

In [61]:
# Sort all models from highest to lowest F1-score
model_results = model_results.sort_values(
    by='F1-score',
    ascending=False
).reset_index(drop=True)

# Display the final sorted comparison table
model_results

                     Model  Accuracy  Precision    Recall  F1-score
0         Tuned Linear SVM  0.893588   0.902553  0.893588  0.882945
1               Linear SVM  0.891161   0.900497  0.891161  0.880313
2  Multinomial Naive Bayes  0.867244   0.869718  0.867244  0.849259
3      Logistic Regression  0.816291   0.812407  0.816291  0.791654

In [63]:
# Save the best tuned Linear SVM model to a file
joblib.dump(svm_grid.best_estimator_,'tuned_linear_svm_model.pkl')

# Confirm that the model has been saved
print("Tuned Linear SVM model saved successfully.")

Tuned Linear SVM model saved successfully.

In [64]:
# Save the TF-IDF vectorizer
joblib.dump(tfidf,'tfidf_vectorizer.pkl')

# Confirm that the vectorizer has been saved
print("TF-IDF vectorizer saved successfully.")

TF-IDF vectorizer saved successfully.